version: '3.9'
services:

  auth-service:
    depends_on:
      - postgres-auth
    build: .
    container_name: auth-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres-auth:5432/authorizationdb
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      SECRET: 9f4KBRiwHuxj/CdmakReFRzhWXVamdVBJZ05HB0vSNqazg8/Jzeg7ZrwfCNN2rArJ4zxQYp2JJPO5iagTeOM/w==
    networks:
      - auth-nt
    mem_limit: 512m

  postgres-auth:
    image: postgres:13
    container_name: postgres-auth
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authorizationdb
    networks:
      - auth-nt
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/query/file.sql:/docker-entrypoint-initdb.d/file.sql
    mem_limit: 512m


volumes:
  postgres_data:

networks:
  auth-nt:
    driver: bridge