package br.com.auth.domain.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TokenResponseDTO implements Serializable {

    private static final long serialVersionUID = 4189152966024287890L;

    @Schema(description = "Token JWT generated by API", example = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9")
    private String token;

    @Schema(description = "Token JWT Type", example = "Bearer")
    private String tokenType;

    @Schema(description = "Time to expires token, default is 10 minutes", example = "2023-06-27T15:04:04.127Z")
    private Instant expiresIn;

}
